### ISSUE TITLE
Sample FSM data corrupted

### ISSUE THREAD

**Issue by migeed-z** [migeed-z/retic_performance#17]
The following configs in the output file are corrupted:

28522 - 28542
34131 - 34930
35331 - 36630
37448 - 37947
38171 - 38670
39321 to end of file

total: 4615 configs

**Comment by bennn** [comment]
Just reset the inputs & outputs for fsm.
- 2458 configs finished
- 521838 left

[fsm_output.txt](https://github.com/migeed-z/retic_performance/files/562455/fsm_output.txt)
[fsm_input.txt.tar.gz](https://github.com/migeed-z/retic_performance/files/562456/fsm_input.txt.tar.gz)

**Comment by bennn** [comment]
also removed a few duplicates from slowSHA
- 9284 done
- 121788 missing

[slowSHA.tar.gz](https://github.com/migeed-z/retic_performance/files/562542/slowSHA.tar.gz)

**Comment by bennn** [comment]
- [X] Double-check the FSM inputs. The recent logs are giving errors for modules like `Other/4.py` and `Utilities/46.py`. Probably because of invalid configurations. (See attached for more errors)
- Yep, `Other.py` has only 4 configurations and `Utilities.py` has only 8

[scary_output.txt](https://github.com/migeed-z/retic_performance/files/573404/scary_output.txt)

**Comment by bennn** [comment]
Solution: the configurations were in the wrong order
- right = alphabetical = Automata, Other, Population, Utilities, main
- wrong = Automata, main, Other, Population, Utilities

(work-around: use consistent case conventions in filenames!)

Here are new inputs:
[fsm-input-2016-11-05.tar.gz](https://github.com/migeed-z/retic_performance/files/573467/fsm-input-2016-11-05.tar.gz)

It doesn't matter that previous outputs were generated by karst from a list-of-configs generated by a computer using the "wrong" order. Because karst was using the right order, and there's a non-empty intersection of "wrong order" and "right order" configurations -- only files in the intersection run without error.
